config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :teams
  root 'home#index'
  resources :users
  resources :wallets, only: :show do
    get '/new/deposit', to: 'wallets#new_deposit'
    get '/new/withdraw', to: 'wallets#new_withdraw'
    get '/new/transfer', to: 'wallets#new_transfer'
    post 'deposit', to: 'wallets#deposit'
    post 'withdraw', to: 'wallets#withdraw'
    post 'transfer', to: 'wallets#transfer'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
    include AccountHandler

    validates :name, :code, :company, presence: true
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]

  def index
    @stocks = Stock.all
  end

  def show
  end

  def new
    @stock = Stock.new
  end

  def edit
  end

  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def stock_params
      params.require(:stock).permit(:name, :code, :company)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<div class="button-fit">
  <h1 class="margin-h1">Stocks</h1>
  <p class="line"></p>
  <div class="button button-table"><%= link_to 'New', new_stock_path, class: "btn btn-outline-primary"%></div>
  <div class="button button-table"><%= link_to 'Back', root_path, class: "btn btn-outline-primary"%></div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Code</th>
      <th scope="col">Company</th>
      <th scope="col">Wallet Number</th>
      <th scope="col">Wallet Balance</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each_with_index do |stock, idx| %>
    <tr>
      <th scope="row"><%= idx + 1 %></th>
      <td><%= stock.name %></td>
      <td><%= stock.code %></td>
      <td><%= stock.company %></td>
      <td><%= stock.wallet_account.account_number %></td>
      <td><%= stock.wallet_account.balance %></td>
      <td>
          <div class="button button-table"><%= link_to 'Show', stock_path(stock), class: "btn btn-outline-primary"%></div>  
          <div class="button button-table"><%= link_to 'Edit', edit_stock_path(stock), class: "btn btn-outline-primary"%></div>
          <div class="button button-table"><%= link_to 'Wallet', wallet_path(stock.wallet_account), class: "btn btn-outline-primary"%></div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @stock.code %>
</p>

<p>
  <strong>Company:</strong>
  <%= @stock.company %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>