config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :teams
  root 'home#index'
  resources :users
  resources :wallets, only: :show do
    get '/new/deposit', to: 'wallets#new_deposit'
    get '/new/withdraw', to: 'wallets#new_withdraw'
    get '/new/transfer', to: 'wallets#new_transfer'
    post 'deposit', to: 'wallets#deposit'
    post 'withdraw', to: 'wallets#withdraw'
    post 'transfer', to: 'wallets#transfer'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    include AccountHandler

    validates :first_name, :last_name, :email, presence: true
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="button-fit">
  <h1 class="margin-h1">Users</h1>
  <p class="line"></p>
  <div class="button button-table"><%= link_to 'New', new_user_path, class: "btn btn-outline-primary"%></div>
  <div class="button button-table"><%= link_to 'Back', root_path, class: "btn btn-outline-primary"%></div>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">FirstName</th>
      <th scope="col">LastName</th>
      <th scope="col">Email</th>
      <th scope="col">Wallet Number</th>
      <th scope="col">Wallet Balance</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, idx| %>
    <tr>
      <th scope="row"><%= idx + 1 %></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.wallet_account.account_number %></td>
      <td><%= user.wallet_account.balance %></td>
      <td>
          <div class="button button-table"><%= link_to 'Show', user_path(user), class: "btn btn-outline-primary"%></div>  
          <div class="button button-table"><%= link_to 'Edit', edit_user_path(user), class: "btn btn-outline-primary"%></div>
          <div class="button button-table"><%= link_to 'Wallet', wallet_path(user.wallet_account), class: "btn btn-outline-primary"%></div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>