config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :teams
  root 'home#index'
  resources :users
  resources :wallets, only: :show do
    get '/new/deposit', to: 'wallets#new_deposit'
    get '/new/withdraw', to: 'wallets#new_withdraw'
    get '/new/transfer', to: 'wallets#new_transfer'
    post 'deposit', to: 'wallets#deposit'
    post 'withdraw', to: 'wallets#withdraw'
    post 'transfer', to: 'wallets#transfer'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
    before_action :find_wallet

    def show
       @transactions = AccountTransaction.where(origin: @account).or(AccountTransaction.where(recipient: @account))
    end
    
    def new_deposit
    end

    def deposit
        @bank_account = Account.find_or_create_by(account_type: :bank_account, owner: @account, currency: Account::ACCOUNT_CURRENCY)

        errors = WalletTransaction::ValidateTransaction.new(account_params[:amount], "deposit", @bank_account, @account).perform

        if errors.size > 0
            flash[:danger] = errors
            render 'new_deposit'
        else
            wallet = WalletTransaction::TransactionActivity.new(account_params[:amount], "deposit", @bank_account, @account).perform

            flash[:success] = "The transaction have been made successfully"

            redirect_to wallet_new_deposit_path(@account.owner.wallet_account)
        end
    end
    
    def new_withdraw
    end

    def withdraw
        errors = WalletTransaction::ValidateTransaction.new(account_params[:amount], "withdraw", @account).perform

        if errors.size > 0
            flash[:danger] = errors
            render 'new_withdraw'
        else
            wallet = WalletTransaction::TransactionActivity.new(account_params[:amount], "withdraw", @account).perform

            flash[:success] = "The transaction have been made successfully"

            redirect_to wallet_new_withdraw_path(@account.owner.wallet_account)
        end
    end
    
    def new_transfer
    end

    def transfer
        @recipient = Account.wallet.find_by(account_number: account_params[:account_number])

        errors = WalletTransaction::ValidateTransaction.new(account_params[:amount], "transfer", @account, @recipient).perform

        if errors.size > 0
            flash[:danger] = errors
            render 'new_transfer'
        else
            wallet = WalletTransaction::TransactionActivity.new(account_params[:amount], "transfer", @account, @recipient).perform

            flash[:success] = "The transaction have been made successfully"

            redirect_to wallet_new_transfer_path(@account.owner.wallet_account)
        end
    end

    private

    def find_wallet
      @account = Account.wallet.find_by(id: params[:id]) || Account.wallet.find_by(id: params[:wallet_id])
    end

    def account_params
      params.require(:account).permit(:amount, :transaction_type, :account_number)
    end
end

app/views/wallets/new_deposit.html.erb
<% flash.each do |name, messages| %>
  <% if messages.is_a?(String) %>
    <p class="alert alert-success"><%= messages %></p>
  <% elsif messages.is_a?(Array) && messages.size == 1 %>
    <p class="alert alert-danger"><%= messages.first %></p>
  <% else %>
    <div class="alert alert-danger">
      <ul>
      <% messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
<h4>
  Adding funds to wallet number: <%= @account.account_number %>
  <br/>
  Current balance: <%= @account.balance %>
</h3>
<small>Note: Funds will be coming from the bank account</small>
<p>
  <%= form_with model: @account, url: wallet_deposit_path(id: @account.id), method: :post, local: true do |form| %>
    <%= form.label 'Amount:' %>
    <%= form.text_field 'amount', value: 0 %>
    <%= form.submit 'Create Transaction' %>
  <% end %>
</p>
<%= link_to 'Back', wallet_path(@account.owner.wallet_account) %>

app/views/wallets/new_transfer.html.erb
<% flash.each do |name, messages| %>
  <% if messages.is_a?(String) %>
    <p class="alert alert-success"><%= messages %></p>
  <% elsif messages.is_a?(Array) && messages.size == 1 %>
    <p class="alert alert-danger"><%= messages.first %></p>
  <% else %>
    <div class="alert alert-danger">
      <ul>
      <% messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
<h3>
  Transfer funds from wallet number: <%= @account.account_number %>
  <br/>
  Current balance: <%= @account.balance %>
</h3>
<p>
  <%= form_with model: @account, url: wallet_transfer_path(@account.id), method: :post, local: true do |form| %>
    <%= form.label "To Account (Wallet Number):" %>
    <%= form.number_field "account_number" %>
    <%= form.label "Amount:" %>
    <%= form.text_field "amount", value: 0 %>
    <%= form.submit "Create Transaction" %>
  <% end %>
</p>
<%= link_to 'Back', wallet_path(@account.owner.wallet_account) %>

app/views/wallets/new_withdraw.html.erb
<% flash.each do |name, messages| %>
  <% if messages.is_a?(String) %>
    <p class="alert alert-success"><%= messages %></p>
  <% elsif messages.is_a?(Array) && messages.size == 1 %>
    <p class="alert alert-danger"><%= messages.first %></p>
  <% else %>
    <div class="alert alert-danger">
      <ul>
      <% messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>
<h4>
  Extracting funds from wallet number: <%= @account.account_number %>
  <br/>
  Current balance: <%= @account.balance %>
</h3>
<p>
  <%= form_with model: @account, url: wallet_withdraw_path(id: @account.id), method: :post, local: true do |form| %>
    <%= form.label 'Amount:' %>
    <%= form.text_field 'amount', value: 0 %>
    <%= form.submit 'Create Transaction' %>
  <% end %>
</p>
<%= link_to 'Back', wallet_path(@account.owner.wallet_account) %>

app/views/wallets/show.html.erb
<div class="container">
  <div class="row wrap-header">
    <div class="col align-text">
     
      Wallet Holder: <strong><%= @account.owner.is_a?(User) ? @account.owner.full_name : @account.owner.name %></strong>
    </div>
    <div class="col align-text">
     Wallet Number: <strong><%= @account.account_number %></strong>
    </div>
    <div class="col align-text">
      Wallet Balance: <strong><%= @account.balance %><%= @account.currency %></strong>
    </div>
    <div class="col-4">
        <div class="button button-table"><%= link_to 'Deposit', wallet_new_deposit_path(@account.owner.wallet_account), class: "btn btn-outline-primary"%></div>  
        <div class="button button-table"><%= link_to 'Withdraw', wallet_new_withdraw_path(@account.owner.wallet_account), class: "btn btn-outline-primary"%></div>
        <div class="button button-table"><%= link_to 'Transfer', wallet_new_transfer_path(@account.owner.wallet_account), class: "btn btn-outline-primary"%></div>
        <% if @account.owner.is_a?(User)%>
          <div class="button button-table"><%= link_to 'Users', users_path, class: "btn btn-outline-primary"%></div>
        <% elsif @account.owner.is_a?(Team) %>
          <div class="button button-table"><%= link_to 'Teams', teams_path, class: "btn btn-outline-primary"%></div>
        <% else %>
          <div class="button button-table"><%= link_to 'Stocks', stocks_path, class: "btn btn-outline-primary"%></div>
        <% end %>
    </div>
  </div>
</div>
<hr/>

<h3>Transactions History</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Type</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each_with_index do |transaction, idx| %>
    <tr>
      <th scope="row"><%= idx + 1 %></th>
      <td><%= transaction.transaction_type %></td>
      <td><%= transaction.origin.account_type %></td>
      <td><%= transaction.recipient ? transaction.recipient.account_type : "withdraw operator" %></td>
      <td><%= transaction.amount %></td>
    </tr>
    <% end %>
  </tbody>
</table>